spring: 
    datasource:
        url: jdbc:mysql://localhost:3306/cafeData
        username: root
        password: emenic2002
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties: 
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
